//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetWeb.HomeBudgetWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap")]
    public interface HomeBudgetWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse HelloWorld(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse> HelloWorldAsync(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HomeBudgetWebServiceSoapChannel : HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeBudgetWebServiceSoapClient : System.ServiceModel.ClientBase<HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap>, HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap {
        
        public HomeBudgetWebServiceSoapClient() {
        }
        
        public HomeBudgetWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeBudgetWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeBudgetWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeBudgetWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap.HelloWorld(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest inValue = new HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest();
            inValue.Body = new HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequestBody();
            HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse retVal = ((HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse> HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap.HelloWorldAsync(HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest inValue = new HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequest();
            inValue.Body = new HomeBudgetWeb.HomeBudgetWebServiceReference.HelloWorldRequestBody();
            return ((HomeBudgetWeb.HomeBudgetWebServiceReference.HomeBudgetWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
