//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PodvrstaTransfera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PodvrstaTransfera()
        {
            this.Transfers = new HashSet<Transfer>();
        }
    
        public int IDPodvrstaTransfera { get; set; }
        public int IDVrstaTransfera { get; set; }
        public string Opis { get; set; }
        public bool Validna { get; set; }
    
        public virtual VrstaTransfera VrstaTransfera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfers { get; set; }
    }
}
