//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int IDTransfer { get; set; }
        public int IDKorisnik { get; set; }
        public int IDPodvrstaTransfera { get; set; }
        public System.DateTime Datum { get; set; }
        public double Iznos { get; set; }
    
        public virtual PodvrstaTransfera PodvrstaTransfera { get; set; }
    }
}
