//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VrstaTransfera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VrstaTransfera()
        {
            this.PodvrstaTransferas = new HashSet<PodvrstaTransfera>();
        }
    
        public int IDVrstaTransfera { get; set; }
        public bool PrihodRashod { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PodvrstaTransfera> PodvrstaTransferas { get; set; }
    }
}
